// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: common.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderType int32

const (
	OrderType_ASC  OrderType = 0
	OrderType_DESC OrderType = 1
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	OrderType_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// 资源类型: 0-All 1-私有资源池 2-公有资源池
type ResourceType int32

const (
	ResourceType_All     ResourceType = 0
	ResourceType_Private ResourceType = 1
	ResourceType_Public  ResourceType = 2
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "All",
		1: "Private",
		2: "Public",
	}
	ResourceType_value = map[string]int32{
		"All":     0,
		"Private": 1,
		"Public":  2,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// 任务来源 1-运营后台, 3-任务计划, 4-CGBundle,5-CGBoost,6-InstanceCure
type Source int32

const (
	Source_Unknown Source = 0
	// 来源于Iaas
	Source_CGBoss        Source = 1
	Source_TaskScheduler Source = 3
	Source_CGBundle      Source = 4
	Source_CGBoost       Source = 5
	Source_InstanceCure  Source = 6
)

// Enum value maps for Source.
var (
	Source_name = map[int32]string{
		0: "Unknown",
		1: "CGBoss",
		3: "TaskScheduler",
		4: "CGBundle",
		5: "CGBoost",
		6: "InstanceCure",
	}
	Source_value = map[string]int32{
		"Unknown":       0,
		"CGBoss":        1,
		"TaskScheduler": 3,
		"CGBundle":      4,
		"CGBoost":       5,
		"InstanceCure":  6,
	}
)

func (x Source) Enum() *Source {
	p := new(Source)
	*p = x
	return p
}

func (x Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Source) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (Source) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Source.Descriptor instead.
func (Source) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

// 多开架构: 0-未知架构 1-单IP 2-多IP
type MultiOpenArch int32

const (
	MultiOpenArch_UnKnown  MultiOpenArch = 0
	MultiOpenArch_SingleIP MultiOpenArch = 1
	MultiOpenArch_MultiIP  MultiOpenArch = 2
)

// Enum value maps for MultiOpenArch.
var (
	MultiOpenArch_name = map[int32]string{
		0: "UnKnown",
		1: "SingleIP",
		2: "MultiIP",
	}
	MultiOpenArch_value = map[string]int32{
		"UnKnown":  0,
		"SingleIP": 1,
		"MultiIP":  2,
	}
)

func (x MultiOpenArch) Enum() *MultiOpenArch {
	p := new(MultiOpenArch)
	*p = x
	return p
}

func (x MultiOpenArch) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MultiOpenArch) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[3].Descriptor()
}

func (MultiOpenArch) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[3]
}

func (x MultiOpenArch) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MultiOpenArch.Descriptor instead.
func (MultiOpenArch) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

// 无请求参数的接口可以使用BaseRequest
type BaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseRequest) Reset() {
	*x = BaseRequest{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequest) ProtoMessage() {}

func (x *BaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequest.ProtoReflect.Descriptor instead.
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 用于分页请求的时候对页面的指定
type PageOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	No            int32                  `protobuf:"varint,1,opt,name=no,proto3" json:"no,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"` // items/page, page size
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageOptions) Reset() {
	*x = PageOptions{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageOptions) ProtoMessage() {}

func (x *PageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageOptions.ProtoReflect.Descriptor instead.
func (*PageOptions) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *PageOptions) GetNo() int32 {
	if x != nil {
		return x.No
	}
	return 0
}

func (x *PageOptions) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *BaseResp              `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Body          *anypb.Any             `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetRet() *BaseResp {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *Response) GetBody() *anypb.Any {
	if x != nil {
		return x.Body
	}
	return nil
}

type Order struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Field string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// 枚举类型: ASC或DESC
	Type          OrderType `protobuf:"varint,2,opt,name=type,proto3,enum=cginstance.OrderType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *Order) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Order) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ASC
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\n" +
	"cginstance\x1a\x17validate/validate.proto\x1a\x19google/protobuf/any.proto\"\r\n" +
	"\vBaseRequest\"H\n" +
	"\bBaseResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"F\n" +
	"\vPageOptions\x12\x17\n" +
	"\x02no\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x02no\x12\x1e\n" +
	"\x04size\x18\x02 \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\xac\x02(\x01R\x04size\"\\\n" +
	"\bResponse\x12&\n" +
	"\x03ret\x18\x01 \x01(\v2\x14.cginstance.BaseRespR\x03ret\x12(\n" +
	"\x04body\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x04body\"H\n" +
	"\x05Order\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.cginstance.OrderTypeR\x04type*\x1e\n" +
	"\tOrderType\x12\a\n" +
	"\x03ASC\x10\x00\x12\b\n" +
	"\x04DESC\x10\x01*0\n" +
	"\fResourceType\x12\a\n" +
	"\x03All\x10\x00\x12\v\n" +
	"\aPrivate\x10\x01\x12\n" +
	"\n" +
	"\x06Public\x10\x02*a\n" +
	"\x06Source\x12\v\n" +
	"\aUnknown\x10\x00\x12\n" +
	"\n" +
	"\x06CGBoss\x10\x01\x12\x11\n" +
	"\rTaskScheduler\x10\x03\x12\f\n" +
	"\bCGBundle\x10\x04\x12\v\n" +
	"\aCGBoost\x10\x05\x12\x10\n" +
	"\fInstanceCure\x10\x06*7\n" +
	"\rMultiOpenArch\x12\v\n" +
	"\aUnKnown\x10\x00\x12\f\n" +
	"\bSingleIP\x10\x01\x12\v\n" +
	"\aMultiIP\x10\x02B\x10Z\x0edemo/api/v1;v1b\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_proto_goTypes = []any{
	(OrderType)(0),      // 0: cginstance.OrderType
	(ResourceType)(0),   // 1: cginstance.ResourceType
	(Source)(0),         // 2: cginstance.Source
	(MultiOpenArch)(0),  // 3: cginstance.MultiOpenArch
	(*BaseRequest)(nil), // 4: cginstance.BaseRequest
	(*BaseResp)(nil),    // 5: cginstance.BaseResp
	(*PageOptions)(nil), // 6: cginstance.PageOptions
	(*Response)(nil),    // 7: cginstance.Response
	(*Order)(nil),       // 8: cginstance.Order
	(*anypb.Any)(nil),   // 9: google.protobuf.Any
}
var file_common_proto_depIdxs = []int32{
	5, // 0: cginstance.Response.ret:type_name -> cginstance.BaseResp
	9, // 1: cginstance.Response.body:type_name -> google.protobuf.Any
	0, // 2: cginstance.Order.type:type_name -> cginstance.OrderType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
