data:
  debug: true
  repoSelector: "mysql"
  mysql:
    driver: mysql
    source: root:mystic@tcp(localhost:3306)/test?charset=utf8mb4&parseTime=true&loc=Local
  redis:
    addr: "localhost:6379"
    password: "mystic"
    db: 0
    pool: 250
    read_timeout: "5s"
    write_timeout: "5s"
    is_cluster: false