// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.22.0
// source: protos/v1/greeter.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type ListGreeterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListGreeterReq) Reset() {
	*x = ListGreeterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_greeter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGreeterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGreeterReq) ProtoMessage() {}

func (x *ListGreeterReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_greeter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGreeterReq.ProtoReflect.Descriptor instead.
func (*ListGreeterReq) Descriptor() ([]byte, []int) {
	return file_protos_v1_greeter_proto_rawDescGZIP(), []int{0}
}

// The response message containing the greetings
type ListGreeterRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body *ListGreeterRsp_Body `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *ListGreeterRsp) Reset() {
	*x = ListGreeterRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_greeter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGreeterRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGreeterRsp) ProtoMessage() {}

func (x *ListGreeterRsp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_greeter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGreeterRsp.ProtoReflect.Descriptor instead.
func (*ListGreeterRsp) Descriptor() ([]byte, []int) {
	return file_protos_v1_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *ListGreeterRsp) GetBody() *ListGreeterRsp_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type Greeter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Greeter Name
	Age  string `protobuf:"bytes,2,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *Greeter) Reset() {
	*x = Greeter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_greeter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Greeter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Greeter) ProtoMessage() {}

func (x *Greeter) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_greeter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Greeter.ProtoReflect.Descriptor instead.
func (*Greeter) Descriptor() ([]byte, []int) {
	return file_protos_v1_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *Greeter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Greeter) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

type ListGreeterRsp_Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greeters []*Greeter `protobuf:"bytes,1,rep,name=greeters,proto3" json:"greeters,omitempty"` // Greeters
}

func (x *ListGreeterRsp_Body) Reset() {
	*x = ListGreeterRsp_Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_greeter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGreeterRsp_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGreeterRsp_Body) ProtoMessage() {}

func (x *ListGreeterRsp_Body) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_greeter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGreeterRsp_Body.ProtoReflect.Descriptor instead.
func (*ListGreeterRsp_Body) Descriptor() ([]byte, []int) {
	return file_protos_v1_greeter_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListGreeterRsp_Body) GetGreeters() []*Greeter {
	if x != nil {
		return x.Greeters
	}
	return nil
}

var File_protos_v1_greeter_proto protoreflect.FileDescriptor

var file_protos_v1_greeter_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1c, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x33, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x47,
	0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x78, 0x0a, 0x0e, 0x4c, 0x69, 0x73,
	0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x65, 0x6d, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x52,
	0x73, 0x70, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x1a, 0x34, 0x0a,
	0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x2c, 0x0a, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x52, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x22, 0x2f, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x61, 0x67, 0x65, 0x32, 0x82, 0x01, 0x0a, 0x0a, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72,
	0x53, 0x76, 0x63, 0x12, 0x74, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x65, 0x72, 0x12, 0x17, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x64, 0x65,
	0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65,
	0x72, 0x52, 0x73, 0x70, 0x22, 0x33, 0xba, 0x47, 0x15, 0x12, 0x13, 0xe8, 0x8e, 0xb7, 0xe5, 0x8f,
	0x96, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0xe5, 0x88, 0x97, 0xe8, 0xa1, 0xa8, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x15, 0x3a, 0x01, 0x2a, 0x22, 0x10, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x65,
	0x65, 0x74, 0x65, 0x72, 0x2f, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x10, 0x5a, 0x0e, 0x64, 0x65, 0x6d,
	0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protos_v1_greeter_proto_rawDescOnce sync.Once
	file_protos_v1_greeter_proto_rawDescData = file_protos_v1_greeter_proto_rawDesc
)

func file_protos_v1_greeter_proto_rawDescGZIP() []byte {
	file_protos_v1_greeter_proto_rawDescOnce.Do(func() {
		file_protos_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_v1_greeter_proto_rawDescData)
	})
	return file_protos_v1_greeter_proto_rawDescData
}

var file_protos_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_v1_greeter_proto_goTypes = []interface{}{
	(*ListGreeterReq)(nil),      // 0: demo.v1.ListGreeterReq
	(*ListGreeterRsp)(nil),      // 1: demo.v1.ListGreeterRsp
	(*Greeter)(nil),             // 2: demo.v1.Greeter
	(*ListGreeterRsp_Body)(nil), // 3: demo.v1.ListGreeterRsp.Body
}
var file_protos_v1_greeter_proto_depIdxs = []int32{
	3, // 0: demo.v1.ListGreeterRsp.body:type_name -> demo.v1.ListGreeterRsp.Body
	2, // 1: demo.v1.ListGreeterRsp.Body.greeters:type_name -> demo.v1.Greeter
	0, // 2: demo.v1.GreeterSvc.ListGreeter:input_type -> demo.v1.ListGreeterReq
	1, // 3: demo.v1.GreeterSvc.ListGreeter:output_type -> demo.v1.ListGreeterRsp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_v1_greeter_proto_init() }
func file_protos_v1_greeter_proto_init() {
	if File_protos_v1_greeter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_v1_greeter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGreeterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_greeter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGreeterRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_greeter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Greeter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_greeter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGreeterRsp_Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_v1_greeter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_v1_greeter_proto_goTypes,
		DependencyIndexes: file_protos_v1_greeter_proto_depIdxs,
		MessageInfos:      file_protos_v1_greeter_proto_msgTypes,
	}.Build()
	File_protos_v1_greeter_proto = out.File
	file_protos_v1_greeter_proto_rawDesc = nil
	file_protos_v1_greeter_proto_goTypes = nil
	file_protos_v1_greeter_proto_depIdxs = nil
}
